spring:
  application:
    name: user-service

  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 6MB
      file-size-threshold: 5MB

  datasource:
    url: jdbc:postgresql://${USER_POSTGRES_HOST:localhost}:${USER_POSTGRES_PORT:5432}/${USER_POSTGRES_DB:diploma}?currentSchema=${USER_DB_DEFAULT_SCHEMA:user_service}
    username: ${USER_POSTGRES_USERNAME:postgres}
    password: ${USER_POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: user_service
    liquibase-schema: user_service

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: user_service

  data:
    redis:
      enabled: ${REDIS_ENABLED:true}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      password: ${REDIS_PASSWORD:}  # optional

  security:
    jwt:
      secret: ${JWT_SECRET}
      access-expiration: ${JWT_ACCESS_EXPIRATION:900000}      # 15 minutes default
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000}  # 24 hours default
    service-whitelist:
      enabled: true
      hosts: [ "127.0.0.1" ]

server:
  port: 8083

grpc:
  server:
    port: 7093
    security:
      enabled: false
  client:
    security-service:
      address: static://localhost:7080
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-time: 30s
      keep-alive-timeout: 5s
    client-custom:
      timeout-seconds: 30
      retry:
        max-attempts: 3
        delay-milliseconds: 1000

kafka:
  enabled: true
  consumer-enabled: false
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  topics:
    user: ${KAFKA_USER_TOPIC:user}
  transactional-outbox:
    enabled: true

aws:
  s3:
    enabled-s3-config: true
    endpoint: ${MINIO_ENDPOINT:http://localhost:9001}
    region: ${MINIO_REGION:eu-north-1}
    access-key-id: ${MINIO_ACCESS_KEY:super_admin}
    secret-access-key: ${MINIO_SECRET_KEY:super_admin}

attachments:
  by-type:
    PROFILE_PICTURE:
      bucket: ${MINIO_PROFILE_PICTURE_BUCKET:user-profile-picture}
      folder: ${MINIO_PROFILE_PICTURE_FOLDER:profile-pictures/}
      public-base-url: ${MINIO_PUBLIC_BASE_URL:http://localhost:9001}
      max-file-size: 5MB
      max-dimension-px: 4096
      cache-control: "public, max-age=31536000, immutable"
      allowed-mime-types:
        - image/jpeg
        - image/png
      variants:
        full:
          size: 256
          quality: 0.85
        mini:
          size: 64
          quality: 0.85

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.grpc_utils: DEBUG