syntax = "proto3";

package user;

import "google/protobuf/timestamp.proto";

option java_package = "com.casualgames.user";
option java_multiple_files = true;

message CreateUserRequest {
  string guid = 1;
  string username = 2;
  string email = 3;
}

message CreateUserResponse {
  string guid = 1;
  string username = 2;
  string email = 3;
  string balance = 4;
  string role = 5;
  string status = 6;
  google.protobuf.Timestamp created_at = 7;
}

service UserService {
  rpc CreateUser (CreateUserRequest) returns (CreateUserResponse);
}