spring:
  application:
    name: game-service

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${GAME_POSTGRES_HOST:localhost}:${GAME_POSTGRES_PORT:5432}/${GAME_POSTGRES_DB:casual_games}?currentSchema=${GAME_DB_DEFAULT_SCHEMA:game_service}
    username: ${GAME_POSTGRES_USERNAME:postgres}
    password: ${GAME_POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: game_service
    liquibase-schema: game_service

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: game_service
        jdbc:
          time_zone: UTC

  data:
    redis:
      enabled: ${REDIS_ENABLED:true}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      password: ${REDIS_PASSWORD:}  # optional

  security:
    jwt:
      secret: ${JWT_SECRET}
      access-expiration: ${JWT_ACCESS_EXPIRATION:600000}
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000}
      public-paths:
        - /game-service/doc/**

server:
  port: 8082

server-url: ${SERVER_URL:http://localhost:8082}
server-route:

kafka:
  enabled: ${KAFKA_ENABLED:true}
  consumer-enabled: true
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  consumer-config:
    "[group.id]": game-service-room-lifecycle
    "[auto.offset.reset]": earliest
  topics:
    room-lifecycle: ${KAFKA_ROOM_LIFECYCLE_TOPIC:room-lifecycle}

logging:
  level:
    org.springframework.web: ${LOG_LEVEL_SPRING_WEB:INFO}

springdoc:
  preLoadingEnabled: true
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
    path: /game-service/doc/api-docs
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    path: /game-service/doc/swagger-ui.html
    operationsSorter: alpha
