-- TABLE TRANSACTIONS --
CREATE TABLE transactions (
    id BIGSERIAL PRIMARY KEY,
    room_id UUID NOT NULL,
    room_type VARCHAR(255) NOT NULL,
    user_guid UUID NOT NULL,
    type VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    amount DECIMAL(19, 2) NOT NULL CHECK (amount >= 0),
    balance_before DECIMAL(19, 2) NOT NULL CHECK (balance_before >= 0),
    balance_after DECIMAL(19, 2) NOT NULL CHECK (balance_after >= 0),
    created_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

ALTER SEQUENCE IF EXISTS transactions_id_seq START WITH 1 INCREMENT BY 15;

CREATE INDEX idx_transactions_user_guid ON transactions(user_guid);
CREATE INDEX idx_transactions_created_at ON transactions(created_at);
CREATE INDEX idx_transactions_room_id ON transactions(room_id);

CREATE UNIQUE INDEX idx_transactions_room_user_unique
ON transactions(room_id, user_guid)
WHERE status IN ('PENDING', 'SUCCESS');

-- TABLE PROCESSED ROOMS --
CREATE TABLE processed_rooms (
    id BIGSERIAL PRIMARY KEY,
    room_id UUID NOT NULL UNIQUE,
    room_type VARCHAR(255) NOT NULL,
    processed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    transaction_count INT NOT NULL,

    CONSTRAINT uq_processed_rooms_room_id UNIQUE (room_id)
);

ALTER SEQUENCE IF EXISTS processed_rooms_id_seq START WITH 1 INCREMENT BY 15;

CREATE INDEX idx_processed_rooms_type ON processed_rooms(room_type);
CREATE INDEX idx_processed_rooms_processed_at ON processed_rooms(processed_at);

-- TABLE TRANSACTION SUMMARIES --
CREATE TABLE transaction_summaries (
    id BIGSERIAL PRIMARY KEY,
    user_guid UUID NOT NULL,
    balance_before DECIMAL(19, 2) NOT NULL CHECK (balance_before >= 0),
    balance_after DECIMAL(19, 2) NOT NULL CHECK (balance_after >= 0),
    total_won DECIMAL(19, 2) NOT NULL CHECK (total_won >= 0),
    total_lost DECIMAL(19, 2) NOT NULL CHECK (total_lost >= 0),
    net_profit DECIMAL(19, 2) NOT NULL,
	summary_month DATE NOT NULL,
    created_at TIMESTAMP NOT NULL
);

ALTER SEQUENCE IF EXISTS transaction_summaries_id_seq START WITH 1 INCREMENT BY 10;

CREATE INDEX idx_transaction_summaries_user_guid ON transaction_summaries(user_guid);
CREATE INDEX idx_transaction_summaries_created_at ON transaction_summaries(created_at);
CREATE INDEX idx_transaction_summaries_user_month ON transaction_summaries (user_guid, summary_month);